import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

//components
import Header from "@/components/header";
import Footer from "@/components/footer";

//styled components
import StyledComponentsRegistry from "@/lib/registry";
import { register } from "swiper/element/bundle";

//swiper
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
register();

//custom style
import GlobalStyles from "@/styles/GlobalStyles";
import "@/styles/global.css";

//metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <StyledComponentsRegistry>
        <GlobalStyles />
        <body className={inter.className}>
          <Header />
          <Providers>{children}</Providers>
          <Footer />
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
